name: 'Setup UnRAR Tool'
description: 'Build or download UnRAR CLI tool for the current platform'

runs:
  using: 'composite'
  steps:
    - name: Build UnRAR CLI tool (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        curl -LO https://www.rarlab.com/rar/unrarsrc-7.2.2.tar.gz
        tar -xzf unrarsrc-7.2.2.tar.gz
        cd unrar && make
        mkdir -p ../libs/bin
        cp unrar ../libs/bin/unrar

    - name: Download UnRAR CLI tool (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://www.rarlab.com/rar/unrarw64.exe" -OutFile "unrarw64.exe"
        7z x unrarw64.exe -ounrar_cli -y
        New-Item -ItemType Directory -Force -Path "libs/bin"
        Copy-Item "unrar_cli/UnRAR.exe" -Destination "libs/bin/UnRAR.exe"
